before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    - go vet
builds:
  - goos:
      - linux
      - windows
      - darwin
    main: "./cmd/roll"

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^images:"
      - "^_examples:"
